apiVersion: fission.io/v1
kind: HTTPTrigger
metadata:
  creationTimestamp: null
  name: get-custom-fields-rt
  namespace: default
spec:
  createingress: false
  functionref:
    functionweights: null
    name: get-custom-fields-fn
    type: name
  host: ""
  ingressconfig:
    annotations: null
    host: '*'
    path: /get-custom-fields
    tls: ""
  method: ""
  methods:
  - GET
  prefix: ""
  relativeurl: /get-custom-fields
