include:
- ./func/*
kind: ArchiveUploadSpec
name: func-MalS

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: get-custom-fields-fn-2ddbe429-01d3-4121-80a0-f7448e978875
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: get-custom-fields-env
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://func-MalS
status:
  buildstatus: pending
  lastUpdateTimestamp: "2022-07-12T16:09:34Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: get-custom-fields-fn
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy
      MaxScale: 1
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80
    StrategyType: execution
  concurrency: 500
  environment:
    name: get-custom-fields-env
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: main.get_all_ticket_custom_fields
    packageref:
      name: get-custom-fields-fn-2ddbe429-01d3-4121-80a0-f7448e978875
      namespace: default
  requestsPerPod: 1
  resources: {}
